language: ruby
script : script/cibuild
sudo: false
notifications:
  email: false
branches:
  only:
    - master
rvm:
  - 2.6
  - 2.4
env:
  - ""
  - JEKYLL_VERSION=3.7.4
matrix:
  include:
    - # GitHub Pages
      rvm: 2.5.1
      env: GH_PAGES=true
